recipe: default.v1

assistant_id: 20250123-213614-upbeat-centroid

language: vi
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: RegexEntityExtractor
  - name: DIETClassifier
    constrain_similarities: true
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.4

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true

